/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "administracion": {
        "VALIDATIONS": {
            "NOT_FOUND": {
                "ASEGURADORA": string;
                "CONFIGURACION_ASEGURADORA": string;
                "CONFIGURACION_DOCUMENTAL": string;
                "DOCUMENTO": string;
                "PROYECTO": string;
                "USUARIO": string;
            };
            "EXISTS": {
                "ASEGURADORA": string;
                "CONFIGURACION_ASEGURADORA": string;
                "CONFIGURACION_DOCUMENTAL": string;
                "CONFIGURACION_FIRMA_COTEJO": string;
                "DOCUMENTO": string;
                "PROYECTO": string;
                "USUARIO": string;
                "EMAIL": string;
            };
        };
        "ASEGURADORA": {
            "ERROR": {};
            "SUCCESS": {};
        };
        "CONFIGURACION_ASEGURADORA": {
            "ERROR": {};
            "SUCCESS": {};
        };
        "CONFIGURACION_DOCUMENTAL": {
            "ERROR": {};
            "SUCCESS": {};
        };
        "DOCUMENTO": {
            "ERROR": {};
            "SUCCESS": {};
        };
        "MENU_PERFIL": {
            "ERROR": {};
            "SUCCESS": {};
        };
        "PERMISO_PERFIL": {
            "ERROR": {};
            "SUCCESS": {};
        };
        "PROYECTO": {
            "ERROR": {};
            "SUCCESS": {};
        };
        "PROYECTO_CONFIGURACION": {
            "ERROR": {};
            "SUCCESS": {};
        };
        "USUARIO": {
            "ERROR": {};
            "SUCCESS": {};
        };
    };
    "all": {
        "VALIDATIONS": {
            "ERROR_GENERAL": string;
            "FIELD": {
                "REQUIRED": string;
                "STRING": string;
                "DATE": string;
                "ID_MONGO": string;
                "EMAIL": string;
                "FORMAT": string;
                "ARRAY": string;
                "ARRAY_UNIQUE": string;
                "NUMERIC": string;
                "DECIMAL": string;
            };
            "DATA": {
                "NOT_FOUND": {
                    "GENERAL": string;
                };
                "EXISTS": {
                    "GENERAL": string;
                };
            };
        };
        "MESSAGES": {
            "SUCCESS": {
                "SAVED": string;
                "UPDATED": string;
                "DELETED": string;
                "NOTIFICATION": string;
            };
            "ERROR": {
                "SAVED": string;
                "UPDATED": string;
                "DELETED": string;
                "NOTIFICATION": string;
            };
        };
    };
    "autenticacion": {
        "ACCOUNT": {
            "ERROR": {
                "BLOCKED": string;
                "PREVIOUSLY_ACTIVATED": string;
                "PASSWORD_COMPARISON": string;
                "INACTIVE": string;
                "COMPARE_USER_AND_PASSWORD": string;
            };
            "SUCCESS": {
                "ACTIVATED": string;
            };
        };
    };
    "auth": {
        "MAIL": {
            "VALIDACIONES": {
                "NO_DESTINATARIOS": string;
                "NO_EMAIL_CC": string;
                "EMAIL_INVALID": string;
            };
            "SUCCESS": string;
            "ERROR": string;
        };
        "ACTIVACION_CUENTA": {
            "ASUNTO": string;
            "BODY": {
                "ACTION": string;
                "ACTION_LINK": string;
                "ESTIMADO": string;
                "MESSAGE_ONE": string;
            };
        };
        "RECOVER_PASSWORD": {
            "ASUNTO": string;
            "BODY": {
                "ESTIMADO": string;
                "MESSAGE_ONE": string;
            };
        };
        "CODIGO_AUTENTIFICACION": {
            "ASUNTO": string;
            "BODY": {
                "ACTION": string;
                "ACTION_LINK": string;
                "ESTIMADO": string;
                "MESSAGE_ONE": string;
                "MESSAGE_EXPIRE": string;
            };
        };
    };
    "bitacora": {
        "VALIDATIONS": {
            "NOT_FOUND": {
                "ACTIVIDAD": string;
            };
            "EXISTS": {
                "ACTIVIDAD": string;
            };
        };
    };
    "catalogos": {
        "VALIDATIONS": {
            "NOT_FOUND": {
                "ACTIVIDAD": string;
                "CATEGORIA_DOCUMENTO": string;
                "ESTATUS_USUARIO": string;
                "ESTATUS_ACTIVIDAD": string;
                "ESTATUS_CONTACTO_TELEFONICO": string;
                "ESTATUS_GENERACION_FORMATOS": string;
                "ESTATUS_GENERAL": string;
                "GIRO": string;
                "MOTIVO_RECHAZO": string;
                "NEGOCIO": string;
                "OFICINA": string;
                "PAIS": string;
                "PERFIL": string;
                "PROCESO": string;
                "RAMO": string;
                "RIESGO": string;
                "TIPO_CARGA": string;
                "TIPO_CONTACTO": string;
                "TIPO_LLAMADA": string;
                "TIPO_MOVIMIENTO": string;
                "TIPO_PERSONA": string;
                "UNIDAD": string;
            };
            "EXISTS": {
                "ACTIVIDAD": string;
                "CATEGORIA_DOCUMENTO": string;
                "ESTATUS_USUARIO": string;
                "ESTATUS_ACTIVIDAD": string;
                "ESTATUS_CONTACTO_TELEFONICO": string;
                "ESTATUS_GENERACION_FORMATOS": string;
                "ESTATUS_GENERAL": string;
                "GIRO": string;
                "MOTIVO_RECHAZO": string;
                "NEGOCIO": string;
                "OFICINA": string;
                "PAIS": string;
                "PERFIL": string;
                "PROCESO": string;
                "RAMO": string;
                "RIESGO": string;
                "TIPO_CARGA": string;
                "TIPO_CONTACTO": string;
                "TIPO_LLAMADA": string;
                "TIPO_MOVIMIENTO": string;
                "TIPO_PERSONA": string;
                "UNIDAD": string;
            };
            "MIN_VALUE_CLAVE": string;
        };
    };
    "core": {
        "VALIDATIONS": {
            "NOT_FOUND": {
                "CONTACTO_TELEFONICO": string;
                "FOLIO": string;
                "FOLIO_LAYOUT": string;
                "INFORMACION_CONTACTO": string;
                "POLIZA": string;
                "TELEFONO_CORRESPONDENCIA": string;
                "TITULAR": string;
            };
            "EXISTS": {
                "CONTACTO_TELEFONICO": string;
                "FOLIO": string;
                "FOLIO_LAYOUT": string;
                "INFORMACION_CONTACTO": string;
                "POLIZA": string;
                "TELEFONO_CORRESPONDENCIA": string;
                "TITULAR": string;
            };
        };
        "FOLIO": {
            "ERROR": {
                "OTHER_PROYECTO": string;
            };
            "SUCCESS": {};
        };
        "REPORTE": {
            "SUCCESS": {
                "SEND_REPORT": string;
            };
        };
    };
    "expediente": {
        "FILE": {
            "SUCCESS": {
                "SAVE": string;
                "UPLOAD": string;
                "DOWNLOAD": string;
                "DELETE": string;
            };
            "ERROR": {
                "SAVE": string;
                "UPLOAD": string;
                "DOWNLOAD": string;
                "DELETE": string;
                "REQUIRED": string;
                "EXCEEDS_SIZE": string;
                "FORMAT": string;
                "NOT_FOUND": string;
            };
        };
    };
    "fianzas": {
        "MAIL": {
            "VALIDACIONES": {
                "NO_DESTINATARIOS": string;
                "NO_EMAIL_CC": string;
            };
            "SUCCESS": string;
            "ERROR": string;
        };
        "CORE": {
            "FORMATO_ENTREGADO": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                };
            };
            "FIRMA_EJECUTIVO": {
                "ASUNTO": string;
                "BODY": {
                    "ESTIMADO": string;
                    "MESSAGE_ONE": string;
                };
            };
            "FIRMA_EJECUTIVO_REVISION_DOCUMENTAL": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "CORREO": string;
                    "DOCUMENTOS": string;
                    "ENLACE": string;
                    "MESSAGE_FIVE": string;
                    "MESSAGE_FOUR": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_TWO": string;
                    "NRO_CLIENTE": string;
                };
            };
            "FOLIO": {
                "ASUNTO": string;
                "BODY": {
                    "ESTIMADO": string;
                    "MESSAGE_ONE": string;
                };
            };
            "SOLICITUD_FIRMA_ASEGURADO": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "OBSERVACIONES": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_THREE": string;
                    "NRO_CLIENTE": string;
                    "CORREO": string;
                };
            };
            "FORMATOS_FIRMADOS": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "MENSAJE_GENERICO": {
                "MESSAGE_ONE": string;
                "MESSAGE_TWO": string;
                "MESSAGE_THREE": string;
                "MESSAGE_FOUR": string;
            };
            "SOLICITUD": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "CORREO": string;
                    "DOCUMENTOS": string;
                    "MESSAGE_FIVE": string;
                    "MESSAGE_FOUR": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_SIX": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_TWO": string;
                    "NRO_CLIENTE": string;
                };
            };
            "DATOS_CONTACTO": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                };
            };
            "NO_CONTINUA_PROCESO": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                };
            };
            "FIRMA_DE_DOCUMENTOS": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_FOUR": string;
                    "NRO_CLIENTE": string;
                    "CORREO": string;
                };
            };
            "REVISION_DOCUMENTAL": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "CORREO": string;
                    "DOCUMENTOS": string;
                    "MESSAGE_FIVE": string;
                    "MESSAGE_FOUR": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_SIX": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_SEVEN": string;
                    "MESSAGE_EIGHT": string;
                    "NRO_CLIENTE": string;
                };
            };
            "FISICOS_ENVIADOS": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "REVISION_DOCUMENTACION_FISICA": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "RECOLECCION_FISICOS": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "NRO_CLIENTE": string;
                    "CORREO": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_FOUR": string;
                };
            };
            "SOLICITUD_FIRMA_EJECUTIVO": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "REVISION_DE_FORMATOS": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "GENERACION_DE_FORMATOS": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "GENERACION_DE_FORMATOSV2": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_FOUR": string;
                };
            };
            "RECEPCION_DOCUMENTOS": {
                "ASUNTO": string;
                "BODY": {
                    "ESTIMADO": string;
                    "MESSAGE_ONE": string;
                };
            };
        };
        "PORTAL": {
            "RECEPCION_DOCUMENTOS": {
                "ASUNTO": string;
                "BODY": {
                    "ESTIMADO": string;
                    "MESSAGE_ONE": string;
                };
            };
        };
        "ACTIVACION_CUENTA": {
            "ASUNTO": string;
            "BODY": {
                "ACTION": string;
                "ACTION_LINK": string;
                "ESTIMADO": string;
                "MESSAGE_ONE": string;
            };
        };
        "RECOVER_PASSWORD": {
            "ASUNTO": string;
            "BODY": {
                "ESTIMADO": string;
                "MESSAGE_ONE": string;
            };
        };
        "CODIGO_AUTENTIFICACION": {
            "ASUNTO": string;
            "BODY": {
                "ACTION": string;
                "ACTION_LINK": string;
                "ESTIMADO": string;
                "MESSAGE_ONE": string;
                "MESSAGE_EXPIRE": string;
            };
        };
        "CODIGO_VERIFICACION_MFA": {
            "ASUNTO": string;
        };
    };
    "notificaciones": {
        "MAIL": {
            "VALIDACIONES": {
                "NO_DESTINATARIOS": string;
                "NO_EMAIL_CC": string;
            };
            "SUCCESS": string;
            "ERROR": string;
        };
        "CORE": {
            "FORMATO_ENTREGADO": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                };
            };
            "FIRMA_EJECUTIVO": {
                "ASUNTO": string;
                "BODY": {
                    "ESTIMADO": string;
                    "MESSAGE_ONE": string;
                };
            };
            "FIRMA_EJECUTIVO_REVISION_DOCUMENTAL": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "CORREO": string;
                    "DOCUMENTOS": string;
                    "ENLACE": string;
                    "MESSAGE_FIVE": string;
                    "MESSAGE_FOUR": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_TWO": string;
                    "NRO_CLIENTE": string;
                };
            };
            "FOLIO": {
                "ASUNTO": string;
                "BODY": {
                    "ESTIMADO": string;
                    "MESSAGE_ONE": string;
                };
            };
            "SOLICITUD_FIRMA_ASEGURADO": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "OBSERVACIONES": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_THREE": string;
                    "NRO_CLIENTE": string;
                    "CORREO": string;
                };
            };
            "FORMATOS_FIRMADOS": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "MENSAJE_GENERICO": {
                "MESSAGE_ONE": string;
                "MESSAGE_TWO": string;
                "MESSAGE_THREE": string;
                "MESSAGE_FOUR": string;
            };
            "SOLICITUD": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "CORREO": string;
                    "DOCUMENTOS": string;
                    "MESSAGE_FIVE": string;
                    "MESSAGE_FOUR": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_SIX": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_TWO": string;
                    "NRO_CLIENTE": string;
                };
            };
            "DATOS_CONTACTO": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                };
            };
            "NO_CONTINUA_PROCESO": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                };
            };
            "FIRMA_DE_DOCUMENTOS": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_FOUR": string;
                    "NRO_CLIENTE": string;
                    "CORREO": string;
                };
            };
            "REVISION_DOCUMENTAL": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "CORREO": string;
                    "DOCUMENTOS": string;
                    "MESSAGE_FIVE": string;
                    "MESSAGE_FOUR": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_SIX": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_SEVEN": string;
                    "MESSAGE_EIGHT": string;
                    "NRO_CLIENTE": string;
                };
            };
            "FISICOS_ENVIADOS": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "REVISION_DOCUMENTACION_FISICA": {
                "ASUNTO": string;
                "BODY": {
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "RECOLECCION_FISICOS": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "NRO_CLIENTE": string;
                    "CORREO": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_FOUR": string;
                };
            };
            "SOLICITUD_FIRMA_EJECUTIVO": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "REVISION_DE_FORMATOS": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "GENERACION_DE_FORMATOS": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                };
            };
            "GENERACION_DE_FORMATOSV2": {
                "ASUNTO": string;
                "BODY": {
                    "TITULO": string;
                    "APRECIABLE": string;
                    "MESSAGE_ONE": string;
                    "MESSAGE_TWO": string;
                    "MESSAGE_THREE": string;
                    "MESSAGE_FOUR": string;
                };
            };
            "RECEPCION_DOCUMENTOS": {
                "ASUNTO": string;
                "BODY": {
                    "ESTIMADO": string;
                    "MESSAGE_ONE": string;
                };
            };
        };
        "PORTAL": {
            "RECEPCION_DOCUMENTOS": {
                "ASUNTO": string;
                "BODY": {
                    "ESTIMADO": string;
                    "MESSAGE_ONE": string;
                };
            };
        };
        "ACTIVACION_CUENTA": {
            "ASUNTO": string;
            "BODY": {
                "ACTION": string;
                "ACTION_LINK": string;
                "ESTIMADO": string;
                "MESSAGE_ONE": string;
            };
        };
        "RECOVER_PASSWORD": {
            "ASUNTO": string;
            "BODY": {
                "ESTIMADO": string;
                "MESSAGE_ONE": string;
            };
        };
        "CODIGO_AUTENTIFICACION": {
            "ASUNTO": string;
            "BODY": {
                "ACTION": string;
                "ACTION_LINK": string;
                "ESTIMADO": string;
                "MESSAGE_ONE": string;
                "MESSAGE_EXPIRE": string;
            };
        };
        "CODIGO_VERIFICACION_MFA": {
            "ASUNTO": string;
        };
        "TASK": {
            "RECORDATORIO": {
                "ASUNTO": string;
            };
        };
    };
    "server": {
        "STATUS_CODE": {
            "400": string;
            "401": string;
            "404": string;
            "408": string;
            "500": string;
            "502": string;
        };
        "JWTOKEN": {
            "ERROR": {
                "USUARIO": string;
                "PROYECTO": string;
                "ROL": string;
            };
        };
    };
    "workflow": {
        "VALIDATIONS": {
            "NOT_FOUND": {
                "ACTIVIDAD": string;
                "ACTIVIDADES": string;
            };
            "EXISTS": {
                "ACTIVIDAD": string;
                "ACTIVIDADES": string;
            };
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
