export enum ELayoutColumnType {
  NUMERIC,
  ALPHANUMERIC,
  EMAIL,
  EMAIL_MULTIPLE_WITH_SEPARATOR,
  DATE_WITH_FORMAT,
  CATALOG,
  TELEFONO_CORRESPONDENCIA,
}

export enum ELayoutColumns {
  A_CLIENTE,
  B_NOM_CLIENTE,
  C_CVE_EJECUTIVO,
  D_NOM_EJECUTIVO,
  E_UNIDAD,
  F_DES_UNIDAD,
  G_NOM_RIESGO,
  H_CONTACTO_CORRESPONDENCIA,
  I_EMAIL_CORRESPONDENCIA,
  J_TELEFONO_CORRESPONDENCIA,
  K_TIPO_CONTACTO,
  L_ASEGURADORA,
  M_OFICINA,
  N_FECHA_VIGENCIA,
  O_TIPO_MOVIMIENTO,
  P_TIPO_PERSONA,
  Q_GIRO
}
