export enum EMimeTypes {
  ".bmp" = "image/bmp",
  ".csv" = "text/csv",
  ".doc" = "application/msword",
  ".docx" = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ".gif" = "image/gif",
  ".ico" = "image/vnd.microsoft.icon",
  ".jpeg" = "image/jpeg",
  ".jpg" = "image/jpeg",
  ".png" = "image/png",
  ".pdf" = "application/pdf",
  ".ppt" = "application/vnd.ms-powerpoint",
  ".pptx" = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  ".rar" = "application/vnd.rar",
  ".svg" = "image/svg+xml",
  ".txt" = "text/plain",
  ".xls" = "application/vnd.ms-excel",
  ".xlsx" = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ".xml" = "XML",
  ".zip" = "application/zip",
}