export const EstatusBitacoraConsts = {
  NONE: '',
  ALTA_FOLIO: 'Alta folio',
  CORRECION_DE_FORMATOS: 'Corrección de formatos',
  DATOS_DE_CONTACTO_INCORRECTOS: 'Datos de contacto incorrectos',
  EN_ESPERA_DE_FIRMA_ASEGURADO: 'En espera de firma asegurado',
  EN_ESPERA_DE_FIRMA_EJECUTIVO: 'En espera de firma ejecutivo',
  EN_PROCESO_DE_GESTION: 'En proceso de gestión',
  EN_VALIDACION_DE_FIRMAS: 'En validación de firmas',
  FALTA_DE_INFORMACION: 'Falta de información',
  FORMATOS_ENVIADOS_A_ASEGURADORA: 'Formatos enviados a aseguradora',
  GESTIONADO: 'Gestionado',
  PENDIENTE_DE_DOCUMENTACION: 'Pendiente de documentación',
  CANCELADO: 'Cancelado',
};
