export enum ERol {
    ADMINISTRADOR = 1,
    HELPDESK_INTERNO = 2,
    HELPDESK_EXTERNO = 3,
    ANALISTA_INGRESO = 4,
    EJECUTIVO_MESA = 5,
    CONSULTA = 6,
    SUPERVISOR_ANALISTA = 7,
    SUPERVISOR_MESA = 8,
}
