export const SwaggerConsts = {
  BITACORA: { tag: 'Bitacora', controller: 'bitacora' },
  CATALOGS: { tag: 'Catálogos', controller: 'catalogos' },
  CORE: {
    tag: 'Core',
    controller: 'core',
    children: {
      BANDEJA: 'Bandeja',
      CONTACTO_TELEFONICO: 'Contacto telefónico',
      COMENTARIO: 'Comentario',
      CONFIRMACION_ENTREGA: 'Confirmación entrega',
      FOLIO: 'Folio',
      FIRMA_CLIENTE: 'Firma cliente',
      FIRMA_EJECUTIVO: 'Firma ejecutivo',
      LISTA_NEGRA: 'Lista negra',
      TITULAR: 'Titular',
      VALIDACION_DIGITAL: 'Validación digital',
      VALIDACION_FIRMA: 'Validación de firmas',
      VALIDACION_ORIGINAL: 'Validación de originales',
      VALIDACION_AFIANZADORA: 'Validación afianzadora',
      PORTAL: 'Portal asegurado',
      RECOLECCION_FISICOS: 'Recolección fisicos',
      SOLICITUD: 'Solicitud',
    },
  },
  ADMINISTRATION: {
    tag: 'Administración',
    controller: 'administracion',
    children: {
      ASEGURADORA: 'Aseguradora',
      CONFIGURACION_DE_FIRMA_COTEJO: 'Configurador de firma cotejo',
      CONFIGURACION_DOCUMENTAL: 'Configuración documental',
      DOCUMENTO: 'Documento',
      MENU_PERFIL: 'Menú perfil',
      PROYECTO: 'Proyecto',
    },
  },
  AUTHENTICATION: {
    tag: 'Auth',
    controller: 'auth',
  },
  USUARIO: { tag: 'Usuario' },
  EXPEDIENTE: { tag: 'Expediente', controller: 'expedientedigital' },
  WORKFLOW: { tag: 'Workflow', controller: 'workflow' },
};
