export const CABECERA_REPORTE_SEGUIMIENTO = [
	'Número de expediente',
	'Referencia cliente ',
	'Tarea',
	'Analista de mesa',
	'Descripción de unidad', // UEN
	'Cliente',
	'Aseguradora',
	'Proceso',
	'Reproceso',
	'Fecha de solicitud',
	'Fecha de atención',
	'Fecha respuesta del cliente',
	'Fecha de entrega de información completa',
	'Vo.Bo. De documentos',
	'Envío de expediente a aseguradora completo y cotejado',
	'Envío de fisicos ',
	'Vo.Bo de Fisicos',
	'Numero reprocesos para cerrar el expediente',
	'Estatus',
	'Ramo',
	'Observaciones',
	'Ejecutivo',
	'Fecha última operación',
	'Vigencia',
	'1er aviso llamada saliente',
	'1er observación llamada saliente',
	'2do aviso llamada saliente',
	'2do observación llamada saliente',
	'3er aviso llamada saliente',
	'3er observación llamada saliente',
	'1er aviso carga documental',
	'2do aviso carga documental ',
	'3er aviso carga documental ',
	'Documentación faltante.',
];
